controller_list:
  - name: fake_leg1__controller
    joints:
      - joint1_p1
      - joint2_p1
      - joint3_p1
  - name: fake_leg2__controller
    joints:
      - joint1_p2
      - joint2_p2
      - joint3_p2