# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: leg1_
  joint_model_group_pose: l1_zero
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1_p1
    - joint2_p1
    - joint3_p1
    - joint1_p2
    - joint2_p2
    - joint3_p2
    - joint1_p3
    - joint2_p3
    - joint3_p3
    - joint1_p4
    - joint2_p4
    - joint3_p4
    - joint1_p5
    - joint2_p5
    - joint3_p5
    - joint1_p6
    - joint2_p6
    - joint3_p6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: leg1__controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1_p1
      - joint2_p1
      - joint3_p1
  - name: leg2__controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1_p2
      - joint2_p2
      - joint3_p2