controller_list:
  - name: fake_leg1__controller
    joints:
      - joint1_p1
      - joint2_p1
      - joint3_p1
  - name: fake_leg2__controller
    joints:
      - joint1_p2
      - joint2_p2
      - joint3_p2
  - name: fake_leg3__controller
    joints:
      - joint1_p3
      - joint2_p3
      - joint3_p3
  - name: fake_leg4__controller
    joints:
      - joint1_p4
      - joint2_p4
      - joint3_p4
  - name: fake_leg5__controller
    joints:
      - joint1_p5
      - joint2_p5
      - joint3_p5
  - name: fake_leg6__controller
    joints:
      - joint1_p6
      - joint2_p6
      - joint3_p6
  - name: fake_rozh__controller
    joints:
      - joint1_p1
      - joint2_p1
      - joint3_p1
      - joint1_p2
      - joint2_p2
      - joint3_p2
      - joint1_p3
      - joint2_p3
      - joint3_p3
      - joint1_p4
      - joint2_p4
      - joint3_p4
      - joint1_p5
      - joint2_p5
      - joint3_p5
      - joint1_p6
      - joint2_p6
      - joint3_p6